---
- name: Apply common configuration to all nodes
  hosts: all
  roles:
    # variables:
    # ol_update: true: run "dnf update"
    # oci_executor: true: execute ansible playbook from oci lab environment; false: execute from anywhere according to README.md instructions
    - { role: common-setup, ol_update: false, oci_executor: false, install_user: "oracle" } 

- name: Setup ocne-operator node
  hosts: ocne-operator
  roles:
    - { role: operator-setup }

- name: Setup ocne-control node
  hosts: ocne-control
  roles:
    - { role: control-setup }