---
- name: Make sure ~/.ssh exists
  file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Configure SSH (oci executor)
  copy:
    src: "~/.ssh/{{ item.src }}"
    dest: "~/.ssh/{{ item.dest }}"
  loop:
    - {src: "id_rsa", dest: "id_rsa" }
    - {src: "id_rsa.pub", dest: "id_rsa.pub" }
  when: oci_executor == true

- name: Configure SSH (external executor)
  copy:
    src: "~/.ssh/{{ item.src }}"
    dest: "~/.ssh/{{ item.dest }}"
  loop:
    - {src: "ocne_lab_id_rsa", dest: "id_rsa" }
    - {src: "ocne_lab_id_rsa.pub", dest: "id_rsa.pub" }
  when: oci_executor == false

# Update Oracle Linux on all hosts
- name: Update Oracle Linux
  dnf:
    name: '*'
    state: latest
  become: true
  when: ol_update == true

# Reboot all hosts
- name: Reboot 
  reboot:
  become: true
  when: ol_update == true

# Install ocne yum repo
- name: Install ocne yum repo
  dnf:
    name: oracle-olcne-release-el8
    state: latest
  become: true
  
# Disable Swap
- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/swap/ s/^#*/#/' /etc/fstab
  become: true

- name: Authorize ssh access
  authorized_key:
    key: "{{ lookup('file','~/.ssh/id_rsa.pub')}}"
    state: present
  