---
- name: Make sure ~/.ssh exists
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: '0700'
  become: true
  loop:
    - "{{ ansible_user }}"
    - "{{ install_user }}"

- name: Configure SSH - ansible_user (oci executor)
  copy:
    src: "~/.ssh/{{ item.src }}"
    dest: "/home/{{ ansible_user }/.ssh/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  loop:
    - {src: "id_rsa", dest: "id_rsa", mode: "0600" }
    - {src: "id_rsa.pub", dest: "id_rsa.pub", mode: "0644" }
  when: oci_executor == true

- name: Configure SSH - install_user (oci executor)
  copy:
    src: "~/.ssh/{{ item.src }}"
    dest: "/home/{{ install_user }}/.ssh/{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
  become: true
  loop:
    - {src: "id_rsa", dest: "id_rsa", mode: "0600" }
    - {src: "id_rsa.pub", dest: "id_rsa.pub", mode: "0644" }
  when: oci_executor == true

- name: Configure SSH (external executor)
  copy:
    src: "~/.ssh/{{ item.src }}"
    dest: "/home/{{ install_user }}/.ssh/{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: true
  loop:
    - {src: "ocne_lab_id_rsa", dest: "id_rsa", mode: "0600" }
    - {src: "ocne_lab_id_rsa.pub", dest: "id_rsa.pub", mode: "0644" }
  when: oci_executor == false

# Update Oracle Linux on all hosts
- name: Update Oracle Linux
  dnf:
    name: '*'
    state: latest
  become: true
  when: ol_update == true

# Reboot all hosts
- name: Reboot 
  reboot:
  become: true
  when: ol_update == true

# Install ocne yum repo
- name: Install ocne yum repo
  dnf:
    name: oracle-olcne-release-el8
    state: latest
  become: true
  
# Disable Swap
- name: Disable Swap
  shell: |
    swapoff -a
    sed -i '/swap/ s/^#*/#/' /etc/fstab
  become: true

- name: Authorize ssh access
  authorized_key:
    key: "{{ lookup('file','~/.ssh/id_rsa.pub')}}"
    user: "{{ ansible_user }}"
    state: present

- name: Create group olcne
  group:
    name: olcne
    state: present
  become: true

- name: Create user olcne
  user:
    name: olcne
    group: olcne
  become: true