---
- name: Create Certificates Directory
  file:
    path: ~/.olcne/certificates
    state: directory
  become_user: "{{ install_user }}"

- name: Configure Certificates
  file:
    path: "~/.olcne/certificates/{{ item }}"
    src: "/etc/olcne/configs/certificates/production/{{ item }}"
    state: link
  become_user: "{{ install_user }}"
  loop:
    - ca.crt
    - node.crt
    - node.key

- name: Create environment
  shell: olcnectl environment create --config-file ./myenvironment.yaml
  args:
    chdir: "~"
  register: env_create
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: env_create
  when: debug_output == true

- name: Create Kubernetes module
  shell: olcnectl module create --config-file ./myenvironment.yaml
  args:
    chdir: "~"
  register: mod_kube_create
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: mod_kube_create
  when: debug_output == true

- name: Validate Kubernetes module
  shell: olcnectl module validate --config-file myenvironment.yaml
  args:
    chdir: "~"
  register: mod_kube_validate
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: mod_kube_validate
  when: debug_output == true
  
- name: Make sure validation is successfull
  fail:
    msg: Validation of Kubernetes module failed. {{ mod_kube }}
  when: "'Validation of module mycluster succeeded.' not in mod_kube_validate.stdout"

- name: Install Kubernetes module
  shell: olcnectl module install --config-file myenvironment.yaml
  args:
    chdir: "~"
  become_user: "{{ install_user }}"

- name: Validate Deployment of Kubernetes module
  shell: olcnectl module instances --config-file myenvironment.yaml
  args:
    chdir: "~"
  register: deploy_mod_kube
  become_user: "{{ install_user }}"

- name: Output of Validation
  debug:
    var: deploy_mod_kube

- name: "Setup kubectl - make sure $HOME/.kube exists"
  file:
    path: ~/.kube
    state: directory
  become_user: "{{ install_user }}"

- name: "Setup kubectl - add config"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
  become: true

- name: "Setup kubectl - export environment"
  lineinfile:
    path: ~/.bashrc
    line: 'export KUBECONFIG=$HOME/.kube/config'
  become_user: "{{ install_user }}"

- name: Validate kubectl
  shell: kubectl get nodes
  args:
    chdir: "~"
  register: kubectl
  become_user: "{{ install_user }}"

- name: Output of Validation
  debug:
    var: kubectl