---
- name: Create Certificates Directory
  file:
    path: "/home/{{ install_user }}/.olcne/certificates"
    state: directory
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
  become: true 

- name: Configure Certificates
  file:
    path: "/home/{{ install_user }}/.olcne/certificates/{{ item }}"
    src: "/etc/olcne/configs/certificates/production/{{ item }}"
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
    state: link
  become: true 
  loop:
    - ca.cert
    - node.cert
    - node.key

- name: Create environment
  shell: "olcnectl environment create --config-file myenvironment.yaml"
  args:
    chdir: "/home/{{ install_user }}"
  register: env_create
  become: true
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: env_create
  when: debug_output == true

- name: Create Kubernetes module
  shell: olcnectl module create --config-file ./myenvironment.yaml
  args:
    chdir: "/home/{{ install_user }}"
  register: mod_kube_create
  become: true
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: mod_kube_create
  when: debug_output == true

- name: Validate Kubernetes module
  shell: olcnectl module validate --config-file myenvironment.yaml
  args:
    chdir: "/home/{{ install_user }}"
  register: mod_kube_validate
  become: true
  become_user: "{{ install_user }}"

- name: DEBUG output
  debug:
    var: mod_kube_validate
  when: debug_output == true
  
- name: Make sure validation is successfull
  fail:
    msg: Validation of Kubernetes module failed. {{ mod_kube }}
  when: "'Validation of module mycluster succeeded.' not in mod_kube_validate.stdout"

# - name: Install Kubernetes module
#   shell: olcnectl module install --config-file myenvironment.yaml
#   args:
#     chdir: "/home/{{ install_user }}"
#   register: mod_kube_install
#   ignore_errors: true
#   become: true
#   become_user: "{{ install_user }}"
#   delay: 20
#   retries: 5
#   until: "'Please execute the following operations' in mod_kube_install.stdout"

# - name: DEBUG output
#   debug:
#     var: mod_kube_install
#   when: debug_output == true
  