environments:
  - environment-name: myenvironment
    globals:
      api-server: 127.0.0.1:8091
      secret-manager-type: file
      olcne-ca-path: /etc/olcne/configs/certificates/production/ca.cert
      olcne-node-cert-path: /etc/olcne/configs/certificates/production/node.cert
      olcne-node-key-path:  /etc/olcne/configs/certificates/production/node.key
    modules:
      - module: kubernetes
        name: mycluster
        args:
          container-registry: container-registry.oracle.com/olcne
          master-nodes: ocne-control.pub.linuxvirt.oraclevcn.com:8090
          worker-nodes: ocne-worker.pub.linuxvirt.oraclevcn.com:8090
          selinux: enforcing
          restrict-service-externalip: true
          restrict-service-externalip-ca-cert: /etc/olcne/configs/certificates/production/ca.cert
          restrict-service-externalip-tls-cert: /etc/olcne/configs/certificates/restrict_external_ip/production/node.cert
          restrict-service-externalip-tls-key: /etc/olcne/configs/certificates/restrict_external_ip/production/node.key
      - module: istio   
        name: myistio
        args:
          container-registry: container-registry.oracle.com/olcne
          master-nodes: ocne-control.pub.linuxvirt.oraclevcn.com:8090
          worker-nodes: ocne-worker.pub.linuxvirt.oraclevcn.com:8090
          selinux: enforcing
          restrict-service-externalip: true
          restrict-service-externalip-ca-cert: /etc/olcne/configs/certificates/production/ca.cert
          restrict-service-externalip-tls-cert: /etc/olcne/configs/certificates/restrict_external_ip/production/node.cert
          restrict-service-externalip-tls-key: /etc/olcne/configs/certificates/restrict_external_ip/production/node.key
          istio-container-registry: container-registry.oracle.com/olcne 
          istio-helm-module: myhelm 
          helm-kubernetes-module: mycluster
          helm-tiller-image: container-registry.oracle.com/olcne/tiller 