---
# Configure Firewall
- name: Configure Firewall Zone
  firewalld:
    zone: trusted
    interface: cni0
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  
- name: Configure Firewall Ports
  firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    zone: trusted
    interface: cni0
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  with_items:
    - { port: 8090, proto: tcp }
    - { port: 10250, proto: tcp } 
    - { port: 10255, proto: tcp }
    - { port: 8472, proto: udp }
    - { port: 6443, proto: tcp }
    - { port: 10251, proto: tcp }
    - { port: 10252, proto: tcp }
    - { port: 2379, proto: tcp }
    - { port: 2380, proto: tcp }

# Load the Bridge Filtering Module
- name: Load the Bridge Filtering Module
  shell: |
    modprobe br_netfilter
    sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'
  become: true

# Install Platfrom Agent
- name: Install Platform Agent
  dnf:
    name: "olcne-agent,olcne-utils"
    enablerepo: "ol8_olcne15,ol8_addons,ol8_baseos_latest,ol8_appstream,ol8_UEKR6"
    disablerepo: "ol8_olcne12,ol8_olcne13,ol8_olcne14,ol8_developer"
  become: true

# Enable olcne-agent
- name: Enable olcne-agent
  systemd: 
    name: olcne-agent
    enabled: yes
  become: true