---

# Configure Firewall
- name: Configure Firewall
  firewalld:
    port: 8091/tcp
    permanent: yes
    immediate: yes
    state: enabled

# Install OCNE with proper repos 
- name: Install Platform CLI, Platform API Server and utilities
  dnf:
    name: olcnectl olcne-api-server olcne-utils
    enablerepo: "ol8_olcne15,ol8_addons,ol8_baseos_latest,ol8_appstream,ol8_UEKR6"
    disablerepo: "ol8_olcne12,ol8_olcne13,ol8_olcne14,ol8_developer"
  become: true

# Enable olcne-api-server
- name: Enable olcne-api-server
  systemd: 
    name: olcne-api-server
    enabled: yes